### ISSUE TITLE
Bug in number of bombs around tiles

### ISSUE THREAD

**Issue by tolgap** [adauguet/elm-minesweeper#1]
Hi @adauguet 

See screenshot:

![Screen Shot 2019-05-30 at 16 13 15](https://user-images.githubusercontent.com/1763486/58638887-0e993c80-82f6-11e9-8a36-edea95985aed.png)

I would've expected the tiles "1, 2, 1" to actually be "2, 3, 2".

**Comment by adauguet** [comment]
This behaviour happens when you place a flag on a tile where there is no bomb. The crossed bomb is not a bomb, so the numbers are correct to me.

**Comment by tolgap** [comment]
Yup just ran into that, im closing it. Sorry for the wrong issue!
